### PR TITLE
Quick and dirty changes to work with PRAW 4.x.

### PR DESCRIPTION
**Pull request by elnuno**
I've done some changes to get it working with PRAW 4.x. I tried not to break it for 3.x, but didn't install and test that version.

You'll notice that there's no consistency regarding checks: some are version based, others catch ImportErrors while yet others check for attributes. If updating to 4.x is desirable at all, I'd be happy to tidy up changes using the style you prefer.

### CODE REVIEW

**Comment by hidde-jan** [comment]
I'm fine with praw 4 support only, so if you could remove the code for 3 that would be great.

**Comment by justcool393** [comment]
I'm confused. Did you remove the PRAW 4 support? I thought that was the point of this PR.

**Comment by hidde-jan** [comment]
I think this PR was to add both praw 4 and 3 support. I see no reason to keep praw 3 support around. I'm currently looking into using gevent and Greenlets to make a lot of the requests run concurrently. This will make this PR no longer needed.

**Comment by justcool393** [comment]
Yeah, I'm not seeing how we need support for both. OAuth will be useful for us however, and that is decently supported in PRAW 4.

**Comment by hidde-jan** [comment]
Closing this request, because we'll implement praw 4 after some refactoring

**Pull request closed without merging**
